C     -*- fortran -*-
C     This file is autogenerated with f2py (version:1.26.4)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pyinitdsblk(setupfunc)
      external setupfunc
      integer npl
      integer ndset
      integer idsmax(20)
      integer idset
      integer gr_flag
      common /dsblk/ npl,ndset,idsmax,idset,gr_flag
      call setupfunc(npl,ndset,idsmax,idset,gr_flag)
      end

      subroutine f2pyinit_BLNK_(setupfunc)
      external setupfunc
      real(kind=8) mstar
      real(kind=8) sini(10)
      common mstar,sini
      call setupfunc(mstar,sini)
      end


